### ISSUE TITLE
chatroom function not enabled!

### ISSUE THREAD

**Issue by ghost** [salamander-mh/YunXinHelper#3]
chatroom function not enabled!

**Comment by ghost** [comment]
```
"message": "chatroom function not enabled!",
    "code": 403,
    "status_code": 500,
    "debug": {
        "line": 179,
        "file": "E:\\jobs\\fhx-live-s\\vendor\\salamander\\yun-xin-helper\\src\\Api\\Base.php",
        "class": "YunXinHelper\\Exception\\YunXinBusinessException",
        "trace": [
            "#0 E:\\jobs\\fhx-live-s\\vendor\\salamander\\yun-xin-helper\\src\\Api\\ChatRoom.php(100): YunXinHelper\\Api\\Base->sendRequest('chatroom/create...', Array)",
            "#1 E:\\jobs\\fhx-live-s\\app\\Http\\Controllers\\Api\\YunXin.php(87): YunXinHelper\\Api\\ChatRoom->create('sys', '45t7MRNej2NW3xW...')",
            "#2 [internal function]: App\\Http\\Controllers\\Api\\YunXin->chatRoom_create(Object(Dingo\\Api\\Http\\Request))",
```

**Comment by ghost** [comment]
问题解决了
